//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_log
    {
        public int Id { get; set; }
        public int client_id { get; set; }
        public string name { get; set; }
        public string houseNumber { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
