//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component_Requests
    {
        public int request_id { get; set; }
        public int task_id { get; set; }
        public int component_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime request_date { get; set; }
        public string status { get; set; }
        public Nullable<int> issued_quantity { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public string notes { get; set; }
    
        public virtual Assembly_Tasks Assembly_Tasks { get; set; }
        public virtual Component Component { get; set; }
    }
}
