//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Items()
        {
            this.Assembly_Tasks = new HashSet<Assembly_Tasks>();
        }
    
        public int order_item_id { get; set; }
        public int order_id { get; set; }
        public string product_type { get; set; }
        public string configuration { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public string assembly_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assembly_Tasks> Assembly_Tasks { get; set; }
        public virtual Order Order { get; set; }
    }
}
