//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Balance
    {
        public int component_id { get; set; }
        public int current_quantity { get; set; }
        public Nullable<int> min_stock_level { get; set; }
        public Nullable<int> max_stock_level { get; set; }
        public string storage_location { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
