//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int supply_id { get; set; }
        public int component_id { get; set; }
        public int supplier_id { get; set; }
        public Nullable<System.DateTime> supply_date { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public string delivery_status { get; set; }
        public string invoice_number { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
